import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Formulir Feedback Collaboration',
  icons: '/logo-tab-gf.png',
  description: 'Generated by create Puan',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
